{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMaSInvoC4qTQ6Q7q7RffN1",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Aaryan-A/python-budget-management-tool/blob/main/budget_management.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fIV8J3LaZSpn"
      },
      "outputs": [],
      "source": [
        "import tkinter as tk\n",
        "from tkinter import messagebox\n",
        "\n",
        "# Function to calculate the total of all expenses\n",
        "def calculate_total_expenses(expenses_amounts):\n",
        "    return sum(expenses_amounts)\n",
        "\n",
        "# Function to calculate the remaining budget after expenses\n",
        "def calculate_remaining_budget(income, total_expenses):\n",
        "    return income - total_expenses\n",
        "\n",
        "# Function to add a new expense to the list\n",
        "def add_expense():\n",
        "    name = expense_name_entry.get().strip()\n",
        "    amount = expense_amount_entry.get().strip()\n",
        "\n",
        "    if name and amount:\n",
        "        try:\n",
        "            amount = float(amount)\n",
        "\n",
        "            if amount < 0:\n",
        "                messagebox.showerror(\n",
        "                    \"Invalid Input\", \"Expense amount cannot be negative.\"\n",
        "                )\n",
        "                return\n",
        "\n",
        "            expenses_names.append(name)\n",
        "            expenses_amounts.append(amount)\n",
        "            expenses_list.insert(tk.END, f\"{name}: ${amount:.2f}\")\n",
        "\n",
        "            expense_name_entry.delete(0, tk.END)\n",
        "            expense_amount_entry.delete(0, tk.END)\n",
        "\n",
        "        except ValueError:\n",
        "            messagebox.showerror(\n",
        "                \"Invalid Input\", \"Expense amount must be a number.\"\n",
        "            )\n",
        "    else:\n",
        "        messagebox.showerror(\n",
        "            \"Missing Input\",\n",
        "            \"Please provide both name and amount for the expense.\"\n",
        "        )\n",
        "\n",
        "# Function to calculate and display the results\n",
        "def calculate_results():\n",
        "    try:\n",
        "        income = float(income_entry.get().strip())\n",
        "\n",
        "        if income < 0:\n",
        "            messagebox.showerror(\n",
        "                \"Invalid Input\", \"Income cannot be negative.\"\n",
        "            )\n",
        "            return\n",
        "\n",
        "        total_expenses = calculate_total_expenses(expenses_amounts)\n",
        "        remaining_budget = calculate_remaining_budget(\n",
        "            income, total_expenses\n",
        "        )\n",
        "\n",
        "        results_label.config(\n",
        "            text=f\"Income: ${income:.2f}\\n\"\n",
        "                 f\"Total Expenses: ${total_expenses:.2f}\\n\"\n",
        "                 f\"Remaining Budget: ${remaining_budget:.2f}\"\n",
        "        )\n",
        "\n",
        "        if savings_goal_entry.get().strip():\n",
        "            try:\n",
        "                savings_goal = float(savings_goal_entry.get().strip())\n",
        "\n",
        "                if savings_goal < 0:\n",
        "                    messagebox.showerror(\n",
        "                        \"Invalid Input\",\n",
        "                        \"Savings goal cannot be negative.\"\n",
        "                    )\n",
        "                    return\n",
        "\n",
        "                remaining_after_savings = calculate_remaining_budget(\n",
        "                    remaining_budget, savings_goal\n",
        "                )\n",
        "\n",
        "                savings_label.config(\n",
        "                    text=f\"Remaining after Savings Goal: \"\n",
        "                         f\"${remaining_after_savings:.2f}\"\n",
        "                )\n",
        "\n",
        "            except ValueError:\n",
        "                messagebox.showerror(\n",
        "                    \"Invalid Input\", \"Savings goal must be a number.\"\n",
        "                )\n",
        "        else:\n",
        "            savings_label.config(text=\"\")\n",
        "\n",
        "    except ValueError:\n",
        "        messagebox.showerror(\n",
        "            \"Invalid Input\", \"Income must be a number.\"\n",
        "        )\n",
        "\n",
        "root = tk.Tk()\n",
        "root.title(\"Budget Management Tool\")\n",
        "\n",
        "# Create input for yearly income\n",
        "tk.Label(root, text=\"Yearly Income:\").grid(\n",
        "    row=0, column=0, padx=10, pady=5, sticky=\"w\"\n",
        ")\n",
        "income_entry = tk.Entry(root)\n",
        "income_entry.grid(row=0, column=1, padx=10, pady=5)\n",
        "\n",
        "# Create input for expense name\n",
        "tk.Label(root, text=\"Expense Name:\").grid(\n",
        "    row=1, column=0, padx=10, pady=5, sticky=\"w\"\n",
        ")\n",
        "expense_name_entry = tk.Entry(root)\n",
        "expense_name_entry.grid(row=1, column=1, padx=10, pady=5)\n",
        "\n",
        "# Create input for expense amount\n",
        "tk.Label(root, text=\"Expense Amount:\").grid(\n",
        "    row=2, column=0, padx=10, pady=5, sticky=\"w\"\n",
        ")\n",
        "expense_amount_entry = tk.Entry(root)\n",
        "expense_amount_entry.grid(row=2, column=1, padx=10, pady=5)\n",
        "\n",
        "# Button to add expenses\n",
        "add_expense_button = tk.Button(\n",
        "    root, text=\"Add Expense\", command=add_expense\n",
        ")\n",
        "add_expense_button.grid(\n",
        "    row=3, column=0, columnspan=2, pady=10\n",
        ")\n",
        "\n",
        "# Listbox to display all expenses\n",
        "expenses_list = tk.Listbox(root, width=40, height=10)\n",
        "expenses_list.grid(\n",
        "    row=4, column=0, columnspan=2, padx=10, pady=5\n",
        ")\n",
        "\n",
        "# Input for savings goal\n",
        "tk.Label(root, text=\"Savings Goal:\").grid(\n",
        "    row=5, column=0, padx=10, pady=5, sticky=\"w\"\n",
        ")\n",
        "savings_goal_entry = tk.Entry(root)\n",
        "savings_goal_entry.grid(row=5, column=1, padx=10, pady=5)\n",
        "\n",
        "# Label to display results\n",
        "results_label = tk.Label(root, text=\"\", justify=\"left\")\n",
        "results_label.grid(\n",
        "    row=6, column=0, columnspan=2, padx=10, pady=5\n",
        ")\n",
        "\n",
        "# Label to display savings goal results\n",
        "savings_label = tk.Label(root, text=\"\", justify=\"left\")\n",
        "savings_label.grid(\n",
        "    row=7, column=0, columnspan=2, padx=10, pady=5\n",
        ")\n",
        "\n",
        "# Button to calculate results\n",
        "calculate_button = tk.Button(\n",
        "    root, text=\"Calculate\", command=calculate_results\n",
        ")\n",
        "calculate_button.grid(\n",
        "    row=8, column=0, columnspan=2, pady=10\n",
        ")\n",
        "\n",
        "# Initialize empty lists for expenses\n",
        "expenses_names = []\n",
        "expenses_amounts = []\n",
        "\n",
        "root.mainloop()"
      ]
    }
  ]
}